### ISSUE TITLE
LOL WTF.

### ISSUE THREAD

**Issue by sudodaksh** [espice/espice.github.io#1]
Turbo C++ LMAO, you guys are literally asking students to Ride a Horse instead of a Car. GLHF XD

**Comment by parthanium** [comment]
Hi Daksh. Thanks for your concern regarding the successfully concluded competition. ICYMI most kids around here are in CBSE schools where Turbo C++ is the norm and it's pretty much the only compiler they're familiar with. We'll make sure to incorporate your valuable advice next time around. Ciao.

**Comment by sudodaksh** [comment]
@parthanium Even, I'm in CBSE -_- and I'm trying to start a Discussion here. Don't you think it's a bit too much to still use Turbo C++ for all Practical Reasons In Schools? I agree, that not everyone is lucky like me to start programming since they were 8years old. But this ain't right, you're paying to drive a car but instead, you're learning to drive a horse.

**Comment by parthanium** [comment]
Cool. What class? So now that you agree to that fact, I hope it's clear why we made that decision. Competitions are meant to be inclusive and not only for gifted individuals like you. And we always provide CodeBlocks, DevC++ or any other IDE/text editor in case anyone asks for it.

**Comment by sudodaksh** [comment]
I'm in 11th Grade. I think you are right at your part but the Authorities are not (not espice).
